"use strict";
const $=id=>document.getElementById(id);
let samples=[];
function node(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=String(text);if(cls)e.className=cls;return e;}
function jsonBlock(value){return node("pre",JSON.stringify(value,null,2));}
function detail(parent,title,value){const d=node("details");d.append(node("summary",title),jsonBlock(value));parent.append(d);}
function card(parent,title,value,review=false){const c=node("div",undefined,"card "+(review?"review":"pass"));c.append(node("span",title),node("strong",value));parent.append(c);}
async function api(path,options={}){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),8000);try{const response=await fetch(path,{...options,signal:controller.signal,cache:"no-store"});const result=await response.json();if(!response.ok)throw new Error(result.reason_code||"REQUEST_FAILED");return result;}finally{clearTimeout(timer);}}
function selectSample(){const s=samples.find(s=>s.id===$("sample").value);if(!s)return;$("source").value=s.source;$("payload").value=JSON.stringify(s.payload,null,2);$("evidence").value=s.evidence_mode||"verified";$("tool").value=s.tool_call?s.tool_call.name:"default";$("output").value="none";$("results").replaceChildren(node("p","Input changed. Test to refresh the results.","empty"));$("status").textContent="Ready.";}
function showResults(r){const root=$("results");root.replaceChildren();const cards=node("div",undefined,"cards");root.append(cards);card(cards,"Detector",r.detector.decision,r.detector.decision!=="ACCEPT");card(cards,"Context",r.model_context.run_state,r.model_context.run_state==="MANUAL_REVIEW");card(cards,"Tool dispatch",r.permission_guard.state,r.permission_guard.state!=="COMPLETE");card(cards,"Proposed report",r.output_guard.accepted?"ACCEPTED":"REJECTED → fallback",!r.output_guard.accepted);root.append(node("p","External text enters model context: "+String(r.model_context.external_text_included)+" · Simulated operational writes: "+r.simulated_operational_write_effects));detail(root,"Detector findings (safe summaries)",r.detector);detail(root,"Character inspection — human display only",r.human_inspection);detail(root,"Exact minimal model context",r.model_context);detail(root,"Permission guard and simulated calls",{guard:r.permission_guard,calls:r.simulated_executor_calls});detail(root,"Validated report / deterministic fallback",r.output_guard);root.append(node("p",r.limitations.join(" "),"help"));}
$("sample").addEventListener("change",selectSample);
$("test-form").addEventListener("submit",async event=>{event.preventDefault();const b=$("test-button");b.disabled=true;$("status").textContent="Testing…";$("results").replaceChildren(node("p","Waiting for the local controls…","empty"));try{const request={source:$("source").value,payload:JSON.parse($("payload").value),evidence_mode:$("evidence").value,output_change:$("output").value};if($("tool").value!=="default")request.tool_call={name:$("tool").value,arguments:{}};const r=await api("/api/test",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(request)});showResults(r);$("status").textContent="Test completed. Review each boundary separately.";}catch(error){$("status").textContent="Test unavailable — manual review. "+(error instanceof SyntaxError?"Enter valid JSON.":error.name==="AbortError"?"Local request timed out.":error.message);$("results").replaceChildren(node("p","No successful result is available. Your input is preserved.","error"));}finally{b.disabled=false;}});
$("evaluate").addEventListener("click",async()=>{const b=$("evaluate");b.disabled=true;$("evaluation").replaceChildren();$("eval-status").textContent="Running regression cases…";try{const r=await api("/api/evaluation");const root=$("evaluation"),cards=node("div",undefined,"cards");root.append(cards);card(cards,"Expected agreement",r.expected_agreement+" / "+r.cases);card(cards,"Detected unsafe fixtures",r.detected);card(cards,"Detector misses",r.misses,r.misses>0);card(cards,"False positives",r.false_positives,r.false_positives>0);card(cards,"Benign accepted",r.benign_accepted);card(cards,"External text excluded",r.contained_cases+" / "+r.cases);const wrap=node("div",undefined,"scroll"),table=node("table"),head=node("thead"),hr=node("tr");for(const title of ["Case","Decision","Detection outcome","Text excluded"]){const th=node("th",title);th.scope="col";hr.append(th);}head.append(hr);table.append(head);const body=node("tbody");for(const c of r.results){const tr=node("tr");for(const value of [c.case_id,c.decision,c.detection_outcome,c.external_text_excluded?"Yes":"NO"]){tr.append(node("td",value));}body.append(tr);}table.append(body);wrap.append(table);root.append(wrap,node("p",r.limitations.join(" "),"help"));$("eval-status").textContent=r.misses||r.false_positives||r.expected_agreement!==r.cases?"Regression needs attention.":"Selected regression cases agree. This is not a universal security guarantee.";}catch(error){$("eval-status").textContent="Evaluation unavailable — manual review. "+error.message;}finally{b.disabled=false;}});
(async()=>{try{samples=await api("/api/samples");for(const s of samples){const o=node("option",s.name);o.value=s.id;$("sample").append(o);}selectSample();}catch(error){$("status").textContent="Examples unavailable. "+error.message;}})();